# Ansible playbook
---
- hosts: default
  become: true
  gather_facts: False

  vars:
    docroot: /opt/x509tosaml/www

  remote_user: vagrant

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: install apache and modules
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - ntp
      - apache2
      - libapache2-mod-php
      - php-dom

  # Apache

  - name: Start apache Service
    service: name=apache2 enabled=true

  - name: enabled mod_ssl
    apache2_module: name=ssl state=present
    notify:
    - restart apache2

  - name: create virtual host file
    template: src=apache2/vhost.conf dest=/etc/apache2/sites-available/{{ inventory_hostname }}.conf
    notify:
    - restart apache2

  - name: create key pair
    command: openssl genrsa -out /etc/ssl/private/{{ inventory_hostname }}.pem 2048
    args:
      creates: /etc/ssl/private/{{ inventory_hostname }}.pem
    notify:
    - restart apache2

  - name: create self-signed certificate
    command: openssl req -new -x509 -subj '/CN={{ inventory_hostname }}' -key /etc/ssl/private/{{ inventory_hostname }}.pem -out /etc/ssl/certs/{{ inventory_hostname }}.pem -days 3650
    args:
      creates: /etc/ssl/certs/{{ inventory_hostname }}.pem
    notify:
    - restart apache2

  - name: a2ensite {{ inventory_hostname }}
    command: a2ensite {{ inventory_hostname }}
    args:
      creates: /etc/apache2/sites-enabled/{{ inventory_hostname }}.conf
    notify:
    - restart apache2

  handlers:

  - name: restart apache2
    service: name=apache2 state=restarted
